import _cffi_backend
from _typeshed import Incomplete
from enum import IntEnum
from typing import Any


class ConfigFlags(IntEnum):
    FLAG_VSYNC_HINT = 64
    FLAG_FULLSCREEN_MODE = 2
    FLAG_WINDOW_RESIZABLE = 4
    FLAG_WINDOW_UNDECORATED = 8
    FLAG_WINDOW_HIDDEN = 128
    FLAG_WINDOW_MINIMIZED = 512
    FLAG_WINDOW_MAXIMIZED = 1024
    FLAG_WINDOW_UNFOCUSED = 2048
    FLAG_WINDOW_TOPMOST = 4096
    FLAG_WINDOW_ALWAYS_RUN = 256
    FLAG_WINDOW_TRANSPARENT = 16
    FLAG_WINDOW_HIGHDPI = 8192
    FLAG_WINDOW_MOUSE_PASSTHROUGH = 16384
    FLAG_BORDERLESS_WINDOWED_MODE = 32768
    FLAG_MSAA_4X_HINT = 32
    FLAG_INTERLACED_HINT = 65536


class TraceLogLevel(IntEnum):
    LOG_ALL = 0
    LOG_TRACE = 1
    LOG_DEBUG = 2
    LOG_INFO = 3
    LOG_WARNING = 4
    LOG_ERROR = 5
    LOG_FATAL = 6
    LOG_NONE = 7


class KeyboardKey(IntEnum):
    KEY_NULL = 0
    KEY_APOSTROPHE = 39
    KEY_COMMA = 44
    KEY_MINUS = 45
    KEY_PERIOD = 46
    KEY_SLASH = 47
    KEY_ZERO = 48
    KEY_ONE = 49
    KEY_TWO = 50
    KEY_THREE = 51
    KEY_FOUR = 52
    KEY_FIVE = 53
    KEY_SIX = 54
    KEY_SEVEN = 55
    KEY_EIGHT = 56
    KEY_NINE = 57
    KEY_SEMICOLON = 59
    KEY_EQUAL = 61
    KEY_A = 65
    KEY_B = 66
    KEY_C = 67
    KEY_D = 68
    KEY_E = 69
    KEY_F = 70
    KEY_G = 71
    KEY_H = 72
    KEY_I = 73
    KEY_J = 74
    KEY_K = 75
    KEY_L = 76
    KEY_M = 77
    KEY_N = 78
    KEY_O = 79
    KEY_P = 80
    KEY_Q = 81
    KEY_R = 82
    KEY_S = 83
    KEY_T = 84
    KEY_U = 85
    KEY_V = 86
    KEY_W = 87
    KEY_X = 88
    KEY_Y = 89
    KEY_Z = 90
    KEY_LEFT_BRACKET = 91
    KEY_BACKSLASH = 92
    KEY_RIGHT_BRACKET = 93
    KEY_GRAVE = 96
    KEY_SPACE = 32
    KEY_ESCAPE = 256
    KEY_ENTER = 257
    KEY_TAB = 258
    KEY_BACKSPACE = 259
    KEY_INSERT = 260
    KEY_DELETE = 261
    KEY_RIGHT = 262
    KEY_LEFT = 263
    KEY_DOWN = 264
    KEY_UP = 265
    KEY_PAGE_UP = 266
    KEY_PAGE_DOWN = 267
    KEY_HOME = 268
    KEY_END = 269
    KEY_CAPS_LOCK = 280
    KEY_SCROLL_LOCK = 281
    KEY_NUM_LOCK = 282
    KEY_PRINT_SCREEN = 283
    KEY_PAUSE = 284
    KEY_F1 = 290
    KEY_F2 = 291
    KEY_F3 = 292
    KEY_F4 = 293
    KEY_F5 = 294
    KEY_F6 = 295
    KEY_F7 = 296
    KEY_F8 = 297
    KEY_F9 = 298
    KEY_F10 = 299
    KEY_F11 = 300
    KEY_F12 = 301
    KEY_LEFT_SHIFT = 340
    KEY_LEFT_CONTROL = 341
    KEY_LEFT_ALT = 342
    KEY_LEFT_SUPER = 343
    KEY_RIGHT_SHIFT = 344
    KEY_RIGHT_CONTROL = 345
    KEY_RIGHT_ALT = 346
    KEY_RIGHT_SUPER = 347
    KEY_KB_MENU = 348
    KEY_KP_0 = 320
    KEY_KP_1 = 321
    KEY_KP_2 = 322
    KEY_KP_3 = 323
    KEY_KP_4 = 324
    KEY_KP_5 = 325
    KEY_KP_6 = 326
    KEY_KP_7 = 327
    KEY_KP_8 = 328
    KEY_KP_9 = 329
    KEY_KP_DECIMAL = 330
    KEY_KP_DIVIDE = 331
    KEY_KP_MULTIPLY = 332
    KEY_KP_SUBTRACT = 333
    KEY_KP_ADD = 334
    KEY_KP_ENTER = 335
    KEY_KP_EQUAL = 336
    KEY_BACK = 4
    KEY_MENU = 5
    KEY_VOLUME_UP = 24
    KEY_VOLUME_DOWN = 25


class MouseButton(IntEnum):
    MOUSE_BUTTON_LEFT = 0
    MOUSE_BUTTON_RIGHT = 1
    MOUSE_BUTTON_MIDDLE = 2
    MOUSE_BUTTON_SIDE = 3
    MOUSE_BUTTON_EXTRA = 4
    MOUSE_BUTTON_FORWARD = 5
    MOUSE_BUTTON_BACK = 6


class MouseCursor(IntEnum):
    MOUSE_CURSOR_DEFAULT = 0
    MOUSE_CURSOR_ARROW = 1
    MOUSE_CURSOR_IBEAM = 2
    MOUSE_CURSOR_CROSSHAIR = 3
    MOUSE_CURSOR_POINTING_HAND = 4
    MOUSE_CURSOR_RESIZE_EW = 5
    MOUSE_CURSOR_RESIZE_NS = 6
    MOUSE_CURSOR_RESIZE_NWSE = 7
    MOUSE_CURSOR_RESIZE_NESW = 8
    MOUSE_CURSOR_RESIZE_ALL = 9
    MOUSE_CURSOR_NOT_ALLOWED = 10


class GamepadButton(IntEnum):
    GAMEPAD_BUTTON_UNKNOWN = 0
    GAMEPAD_BUTTON_LEFT_FACE_UP = 1
    GAMEPAD_BUTTON_LEFT_FACE_RIGHT = 2
    GAMEPAD_BUTTON_LEFT_FACE_DOWN = 3
    GAMEPAD_BUTTON_LEFT_FACE_LEFT = 4
    GAMEPAD_BUTTON_RIGHT_FACE_UP = 5
    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = 6
    GAMEPAD_BUTTON_RIGHT_FACE_DOWN = 7
    GAMEPAD_BUTTON_RIGHT_FACE_LEFT = 8
    GAMEPAD_BUTTON_LEFT_TRIGGER_1 = 9
    GAMEPAD_BUTTON_LEFT_TRIGGER_2 = 10
    GAMEPAD_BUTTON_RIGHT_TRIGGER_1 = 11
    GAMEPAD_BUTTON_RIGHT_TRIGGER_2 = 12
    GAMEPAD_BUTTON_MIDDLE_LEFT = 13
    GAMEPAD_BUTTON_MIDDLE = 14
    GAMEPAD_BUTTON_MIDDLE_RIGHT = 15
    GAMEPAD_BUTTON_LEFT_THUMB = 16
    GAMEPAD_BUTTON_RIGHT_THUMB = 17


class GamepadAxis(IntEnum):
    GAMEPAD_AXIS_LEFT_X = 0
    GAMEPAD_AXIS_LEFT_Y = 1
    GAMEPAD_AXIS_RIGHT_X = 2
    GAMEPAD_AXIS_RIGHT_Y = 3
    GAMEPAD_AXIS_LEFT_TRIGGER = 4
    GAMEPAD_AXIS_RIGHT_TRIGGER = 5


class MaterialMapIndex(IntEnum):
    MATERIAL_MAP_ALBEDO = 0
    MATERIAL_MAP_METALNESS = 1
    MATERIAL_MAP_NORMAL = 2
    MATERIAL_MAP_ROUGHNESS = 3
    MATERIAL_MAP_OCCLUSION = 4
    MATERIAL_MAP_EMISSION = 5
    MATERIAL_MAP_HEIGHT = 6
    MATERIAL_MAP_CUBEMAP = 7
    MATERIAL_MAP_IRRADIANCE = 8
    MATERIAL_MAP_PREFILTER = 9
    MATERIAL_MAP_BRDF = 10


class ShaderLocationIndex(IntEnum):
    SHADER_LOC_VERTEX_POSITION = 0
    SHADER_LOC_VERTEX_TEXCOORD01 = 1
    SHADER_LOC_VERTEX_TEXCOORD02 = 2
    SHADER_LOC_VERTEX_NORMAL = 3
    SHADER_LOC_VERTEX_TANGENT = 4
    SHADER_LOC_VERTEX_COLOR = 5
    SHADER_LOC_MATRIX_MVP = 6
    SHADER_LOC_MATRIX_VIEW = 7
    SHADER_LOC_MATRIX_PROJECTION = 8
    SHADER_LOC_MATRIX_MODEL = 9
    SHADER_LOC_MATRIX_NORMAL = 10
    SHADER_LOC_VECTOR_VIEW = 11
    SHADER_LOC_COLOR_DIFFUSE = 12
    SHADER_LOC_COLOR_SPECULAR = 13
    SHADER_LOC_COLOR_AMBIENT = 14
    SHADER_LOC_MAP_ALBEDO = 15
    SHADER_LOC_MAP_METALNESS = 16
    SHADER_LOC_MAP_NORMAL = 17
    SHADER_LOC_MAP_ROUGHNESS = 18
    SHADER_LOC_MAP_OCCLUSION = 19
    SHADER_LOC_MAP_EMISSION = 20
    SHADER_LOC_MAP_HEIGHT = 21
    SHADER_LOC_MAP_CUBEMAP = 22
    SHADER_LOC_MAP_IRRADIANCE = 23
    SHADER_LOC_MAP_PREFILTER = 24
    SHADER_LOC_MAP_BRDF = 25
    SHADER_LOC_VERTEX_BONEIDS = 26
    SHADER_LOC_VERTEX_BONEWEIGHTS = 27
    SHADER_LOC_BONE_MATRICES = 28


class ShaderUniformDataType(IntEnum):
    SHADER_UNIFORM_FLOAT = 0
    SHADER_UNIFORM_VEC2 = 1
    SHADER_UNIFORM_VEC3 = 2
    SHADER_UNIFORM_VEC4 = 3
    SHADER_UNIFORM_INT = 4
    SHADER_UNIFORM_IVEC2 = 5
    SHADER_UNIFORM_IVEC3 = 6
    SHADER_UNIFORM_IVEC4 = 7
    SHADER_UNIFORM_SAMPLER2D = 8


class ShaderAttributeDataType(IntEnum):
    SHADER_ATTRIB_FLOAT = 0
    SHADER_ATTRIB_VEC2 = 1
    SHADER_ATTRIB_VEC3 = 2
    SHADER_ATTRIB_VEC4 = 3


class PixelFormat(IntEnum):
    PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1
    PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA = 2
    PIXELFORMAT_UNCOMPRESSED_R5G6B5 = 3
    PIXELFORMAT_UNCOMPRESSED_R8G8B8 = 4
    PIXELFORMAT_UNCOMPRESSED_R5G5B5A1 = 5
    PIXELFORMAT_UNCOMPRESSED_R4G4B4A4 = 6
    PIXELFORMAT_UNCOMPRESSED_R8G8B8A8 = 7
    PIXELFORMAT_UNCOMPRESSED_R32 = 8
    PIXELFORMAT_UNCOMPRESSED_R32G32B32 = 9
    PIXELFORMAT_UNCOMPRESSED_R32G32B32A32 = 10
    PIXELFORMAT_UNCOMPRESSED_R16 = 11
    PIXELFORMAT_UNCOMPRESSED_R16G16B16 = 12
    PIXELFORMAT_UNCOMPRESSED_R16G16B16A16 = 13
    PIXELFORMAT_COMPRESSED_DXT1_RGB = 14
    PIXELFORMAT_COMPRESSED_DXT1_RGBA = 15
    PIXELFORMAT_COMPRESSED_DXT3_RGBA = 16
    PIXELFORMAT_COMPRESSED_DXT5_RGBA = 17
    PIXELFORMAT_COMPRESSED_ETC1_RGB = 18
    PIXELFORMAT_COMPRESSED_ETC2_RGB = 19
    PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA = 20
    PIXELFORMAT_COMPRESSED_PVRT_RGB = 21
    PIXELFORMAT_COMPRESSED_PVRT_RGBA = 22
    PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA = 23
    PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA = 24


class TextureFilter(IntEnum):
    TEXTURE_FILTER_POINT = 0
    TEXTURE_FILTER_BILINEAR = 1
    TEXTURE_FILTER_TRILINEAR = 2
    TEXTURE_FILTER_ANISOTROPIC_4X = 3
    TEXTURE_FILTER_ANISOTROPIC_8X = 4
    TEXTURE_FILTER_ANISOTROPIC_16X = 5


class TextureWrap(IntEnum):
    TEXTURE_WRAP_REPEAT = 0
    TEXTURE_WRAP_CLAMP = 1
    TEXTURE_WRAP_MIRROR_REPEAT = 2
    TEXTURE_WRAP_MIRROR_CLAMP = 3


class CubemapLayout(IntEnum):
    CUBEMAP_LAYOUT_AUTO_DETECT = 0
    CUBEMAP_LAYOUT_LINE_VERTICAL = 1
    CUBEMAP_LAYOUT_LINE_HORIZONTAL = 2
    CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR = 3
    CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE = 4


class FontType(IntEnum):
    FONT_DEFAULT = 0
    FONT_BITMAP = 1
    FONT_SDF = 2


class BlendMode(IntEnum):
    BLEND_ALPHA = 0
    BLEND_ADDITIVE = 1
    BLEND_MULTIPLIED = 2
    BLEND_ADD_COLORS = 3
    BLEND_SUBTRACT_COLORS = 4
    BLEND_ALPHA_PREMULTIPLY = 5
    BLEND_CUSTOM = 6
    BLEND_CUSTOM_SEPARATE = 7


class Gesture(IntEnum):
    GESTURE_NONE = 0
    GESTURE_TAP = 1
    GESTURE_DOUBLETAP = 2
    GESTURE_HOLD = 4
    GESTURE_DRAG = 8
    GESTURE_SWIPE_RIGHT = 16
    GESTURE_SWIPE_LEFT = 32
    GESTURE_SWIPE_UP = 64
    GESTURE_SWIPE_DOWN = 128
    GESTURE_PINCH_IN = 256
    GESTURE_PINCH_OUT = 512


class CameraMode(IntEnum):
    CAMERA_CUSTOM = 0
    CAMERA_FREE = 1
    CAMERA_ORBITAL = 2
    CAMERA_FIRST_PERSON = 3
    CAMERA_THIRD_PERSON = 4


class CameraProjection(IntEnum):
    CAMERA_PERSPECTIVE = 0
    CAMERA_ORTHOGRAPHIC = 1


class NPatchLayout(IntEnum):
    NPATCH_NINE_PATCH = 0
    NPATCH_THREE_PATCH_VERTICAL = 1
    NPATCH_THREE_PATCH_HORIZONTAL = 2


class GuiState(IntEnum):
    STATE_NORMAL = 0
    STATE_FOCUSED = 1
    STATE_PRESSED = 2
    STATE_DISABLED = 3


class GuiTextAlignment(IntEnum):
    TEXT_ALIGN_LEFT = 0
    TEXT_ALIGN_CENTER = 1
    TEXT_ALIGN_RIGHT = 2


class GuiTextAlignmentVertical(IntEnum):
    TEXT_ALIGN_TOP = 0
    TEXT_ALIGN_MIDDLE = 1
    TEXT_ALIGN_BOTTOM = 2


class GuiTextWrapMode(IntEnum):
    TEXT_WRAP_NONE = 0
    TEXT_WRAP_CHAR = 1
    TEXT_WRAP_WORD = 2


class GuiControl(IntEnum):
    DEFAULT = 0
    LABEL = 1
    BUTTON = 2
    TOGGLE = 3
    SLIDER = 4
    PROGRESSBAR = 5
    CHECKBOX = 6
    COMBOBOX = 7
    DROPDOWNBOX = 8
    TEXTBOX = 9
    VALUEBOX = 10
    SPINNER = 11
    LISTVIEW = 12
    COLORPICKER = 13
    SCROLLBAR = 14
    STATUSBAR = 15


class GuiControlProperty(IntEnum):
    BORDER_COLOR_NORMAL = 0
    BASE_COLOR_NORMAL = 1
    TEXT_COLOR_NORMAL = 2
    BORDER_COLOR_FOCUSED = 3
    BASE_COLOR_FOCUSED = 4
    TEXT_COLOR_FOCUSED = 5
    BORDER_COLOR_PRESSED = 6
    BASE_COLOR_PRESSED = 7
    TEXT_COLOR_PRESSED = 8
    BORDER_COLOR_DISABLED = 9
    BASE_COLOR_DISABLED = 10
    TEXT_COLOR_DISABLED = 11
    BORDER_WIDTH = 12
    TEXT_PADDING = 13
    TEXT_ALIGNMENT = 14


class GuiDefaultProperty(IntEnum):
    TEXT_SIZE = 16
    TEXT_SPACING = 17
    LINE_COLOR = 18
    BACKGROUND_COLOR = 19
    TEXT_LINE_SPACING = 20
    TEXT_ALIGNMENT_VERTICAL = 21
    TEXT_WRAP_MODE = 22


class GuiToggleProperty(IntEnum):
    GROUP_PADDING = 16


class GuiSliderProperty(IntEnum):
    SLIDER_WIDTH = 16
    SLIDER_PADDING = 17


class GuiProgressBarProperty(IntEnum):
    PROGRESS_PADDING = 16


class GuiScrollBarProperty(IntEnum):
    ARROWS_SIZE = 16
    ARROWS_VISIBLE = 17
    SCROLL_SLIDER_PADDING = 18
    SCROLL_SLIDER_SIZE = 19
    SCROLL_PADDING = 20
    SCROLL_SPEED = 21


class GuiCheckBoxProperty(IntEnum):
    CHECK_PADDING = 16


class GuiComboBoxProperty(IntEnum):
    COMBO_BUTTON_WIDTH = 16
    COMBO_BUTTON_SPACING = 17


class GuiDropdownBoxProperty(IntEnum):
    ARROW_PADDING = 16
    DROPDOWN_ITEMS_SPACING = 17
    DROPDOWN_ARROW_HIDDEN = 18
    DROPDOWN_ROLL_UP = 19


class GuiTextBoxProperty(IntEnum):
    TEXT_READONLY = 16


class GuiSpinnerProperty(IntEnum):
    SPIN_BUTTON_WIDTH = 16
    SPIN_BUTTON_SPACING = 17


class GuiListViewProperty(IntEnum):
    LIST_ITEMS_HEIGHT = 16
    LIST_ITEMS_SPACING = 17
    SCROLLBAR_WIDTH = 18
    SCROLLBAR_SIDE = 19
    LIST_ITEMS_BORDER_WIDTH = 20


class GuiColorPickerProperty(IntEnum):
    COLOR_SELECTOR_SIZE = 16
    HUEBAR_WIDTH = 17
    HUEBAR_PADDING = 18
    HUEBAR_SELECTOR_HEIGHT = 19
    HUEBAR_SELECTOR_OVERFLOW = 20


class GuiIconName(IntEnum):
    ICON_NONE = 0
    ICON_FOLDER_FILE_OPEN = 1
    ICON_FILE_SAVE_CLASSIC = 2
    ICON_FOLDER_OPEN = 3
    ICON_FOLDER_SAVE = 4
    ICON_FILE_OPEN = 5
    ICON_FILE_SAVE = 6
    ICON_FILE_EXPORT = 7
    ICON_FILE_ADD = 8
    ICON_FILE_DELETE = 9
    ICON_FILETYPE_TEXT = 10
    ICON_FILETYPE_AUDIO = 11
    ICON_FILETYPE_IMAGE = 12
    ICON_FILETYPE_PLAY = 13
    ICON_FILETYPE_VIDEO = 14
    ICON_FILETYPE_INFO = 15
    ICON_FILE_COPY = 16
    ICON_FILE_CUT = 17
    ICON_FILE_PASTE = 18
    ICON_CURSOR_HAND = 19
    ICON_CURSOR_POINTER = 20
    ICON_CURSOR_CLASSIC = 21
    ICON_PENCIL = 22
    ICON_PENCIL_BIG = 23
    ICON_BRUSH_CLASSIC = 24
    ICON_BRUSH_PAINTER = 25
    ICON_WATER_DROP = 26
    ICON_COLOR_PICKER = 27
    ICON_RUBBER = 28
    ICON_COLOR_BUCKET = 29
    ICON_TEXT_T = 30
    ICON_TEXT_A = 31
    ICON_SCALE = 32
    ICON_RESIZE = 33
    ICON_FILTER_POINT = 34
    ICON_FILTER_BILINEAR = 35
    ICON_CROP = 36
    ICON_CROP_ALPHA = 37
    ICON_SQUARE_TOGGLE = 38
    ICON_SYMMETRY = 39
    ICON_SYMMETRY_HORIZONTAL = 40
    ICON_SYMMETRY_VERTICAL = 41
    ICON_LENS = 42
    ICON_LENS_BIG = 43
    ICON_EYE_ON = 44
    ICON_EYE_OFF = 45
    ICON_FILTER_TOP = 46
    ICON_FILTER = 47
    ICON_TARGET_POINT = 48
    ICON_TARGET_SMALL = 49
    ICON_TARGET_BIG = 50
    ICON_TARGET_MOVE = 51
    ICON_CURSOR_MOVE = 52
    ICON_CURSOR_SCALE = 53
    ICON_CURSOR_SCALE_RIGHT = 54
    ICON_CURSOR_SCALE_LEFT = 55
    ICON_UNDO = 56
    ICON_REDO = 57
    ICON_REREDO = 58
    ICON_MUTATE = 59
    ICON_ROTATE = 60
    ICON_REPEAT = 61
    ICON_SHUFFLE = 62
    ICON_EMPTYBOX = 63
    ICON_TARGET = 64
    ICON_TARGET_SMALL_FILL = 65
    ICON_TARGET_BIG_FILL = 66
    ICON_TARGET_MOVE_FILL = 67
    ICON_CURSOR_MOVE_FILL = 68
    ICON_CURSOR_SCALE_FILL = 69
    ICON_CURSOR_SCALE_RIGHT_FILL = 70
    ICON_CURSOR_SCALE_LEFT_FILL = 71
    ICON_UNDO_FILL = 72
    ICON_REDO_FILL = 73
    ICON_REREDO_FILL = 74
    ICON_MUTATE_FILL = 75
    ICON_ROTATE_FILL = 76
    ICON_REPEAT_FILL = 77
    ICON_SHUFFLE_FILL = 78
    ICON_EMPTYBOX_SMALL = 79
    ICON_BOX = 80
    ICON_BOX_TOP = 81
    ICON_BOX_TOP_RIGHT = 82
    ICON_BOX_RIGHT = 83
    ICON_BOX_BOTTOM_RIGHT = 84
    ICON_BOX_BOTTOM = 85
    ICON_BOX_BOTTOM_LEFT = 86
    ICON_BOX_LEFT = 87
    ICON_BOX_TOP_LEFT = 88
    ICON_BOX_CENTER = 89
    ICON_BOX_CIRCLE_MASK = 90
    ICON_POT = 91
    ICON_ALPHA_MULTIPLY = 92
    ICON_ALPHA_CLEAR = 93
    ICON_DITHERING = 94
    ICON_MIPMAPS = 95
    ICON_BOX_GRID = 96
    ICON_GRID = 97
    ICON_BOX_CORNERS_SMALL = 98
    ICON_BOX_CORNERS_BIG = 99
    ICON_FOUR_BOXES = 100
    ICON_GRID_FILL = 101
    ICON_BOX_MULTISIZE = 102
    ICON_ZOOM_SMALL = 103
    ICON_ZOOM_MEDIUM = 104
    ICON_ZOOM_BIG = 105
    ICON_ZOOM_ALL = 106
    ICON_ZOOM_CENTER = 107
    ICON_BOX_DOTS_SMALL = 108
    ICON_BOX_DOTS_BIG = 109
    ICON_BOX_CONCENTRIC = 110
    ICON_BOX_GRID_BIG = 111
    ICON_OK_TICK = 112
    ICON_CROSS = 113
    ICON_ARROW_LEFT = 114
    ICON_ARROW_RIGHT = 115
    ICON_ARROW_DOWN = 116
    ICON_ARROW_UP = 117
    ICON_ARROW_LEFT_FILL = 118
    ICON_ARROW_RIGHT_FILL = 119
    ICON_ARROW_DOWN_FILL = 120
    ICON_ARROW_UP_FILL = 121
    ICON_AUDIO = 122
    ICON_FX = 123
    ICON_WAVE = 124
    ICON_WAVE_SINUS = 125
    ICON_WAVE_SQUARE = 126
    ICON_WAVE_TRIANGULAR = 127
    ICON_CROSS_SMALL = 128
    ICON_PLAYER_PREVIOUS = 129
    ICON_PLAYER_PLAY_BACK = 130
    ICON_PLAYER_PLAY = 131
    ICON_PLAYER_PAUSE = 132
    ICON_PLAYER_STOP = 133
    ICON_PLAYER_NEXT = 134
    ICON_PLAYER_RECORD = 135
    ICON_MAGNET = 136
    ICON_LOCK_CLOSE = 137
    ICON_LOCK_OPEN = 138
    ICON_CLOCK = 139
    ICON_TOOLS = 140
    ICON_GEAR = 141
    ICON_GEAR_BIG = 142
    ICON_BIN = 143
    ICON_HAND_POINTER = 144
    ICON_LASER = 145
    ICON_COIN = 146
    ICON_EXPLOSION = 147
    ICON_1UP = 148
    ICON_PLAYER = 149
    ICON_PLAYER_JUMP = 150
    ICON_KEY = 151
    ICON_DEMON = 152
    ICON_TEXT_POPUP = 153
    ICON_GEAR_EX = 154
    ICON_CRACK = 155
    ICON_CRACK_POINTS = 156
    ICON_STAR = 157
    ICON_DOOR = 158
    ICON_EXIT = 159
    ICON_MODE_2D = 160
    ICON_MODE_3D = 161
    ICON_CUBE = 162
    ICON_CUBE_FACE_TOP = 163
    ICON_CUBE_FACE_LEFT = 164
    ICON_CUBE_FACE_FRONT = 165
    ICON_CUBE_FACE_BOTTOM = 166
    ICON_CUBE_FACE_RIGHT = 167
    ICON_CUBE_FACE_BACK = 168
    ICON_CAMERA = 169
    ICON_SPECIAL = 170
    ICON_LINK_NET = 171
    ICON_LINK_BOXES = 172
    ICON_LINK_MULTI = 173
    ICON_LINK = 174
    ICON_LINK_BROKE = 175
    ICON_TEXT_NOTES = 176
    ICON_NOTEBOOK = 177
    ICON_SUITCASE = 178
    ICON_SUITCASE_ZIP = 179
    ICON_MAILBOX = 180
    ICON_MONITOR = 181
    ICON_PRINTER = 182
    ICON_PHOTO_CAMERA = 183
    ICON_PHOTO_CAMERA_FLASH = 184
    ICON_HOUSE = 185
    ICON_HEART = 186
    ICON_CORNER = 187
    ICON_VERTICAL_BARS = 188
    ICON_VERTICAL_BARS_FILL = 189
    ICON_LIFE_BARS = 190
    ICON_INFO = 191
    ICON_CROSSLINE = 192
    ICON_HELP = 193
    ICON_FILETYPE_ALPHA = 194
    ICON_FILETYPE_HOME = 195
    ICON_LAYERS_VISIBLE = 196
    ICON_LAYERS = 197
    ICON_WINDOW = 198
    ICON_HIDPI = 199
    ICON_FILETYPE_BINARY = 200
    ICON_HEX = 201
    ICON_SHIELD = 202
    ICON_FILE_NEW = 203
    ICON_FOLDER_ADD = 204
    ICON_ALARM = 205
    ICON_CPU = 206
    ICON_ROM = 207
    ICON_STEP_OVER = 208
    ICON_STEP_INTO = 209
    ICON_STEP_OUT = 210
    ICON_RESTART = 211
    ICON_BREAKPOINT_ON = 212
    ICON_BREAKPOINT_OFF = 213
    ICON_BURGER_MENU = 214
    ICON_CASE_SENSITIVE = 215
    ICON_REG_EXP = 216
    ICON_FOLDER = 217
    ICON_FILE = 218
    ICON_SAND_TIMER = 219
    ICON_WARNING = 220
    ICON_HELP_BOX = 221
    ICON_INFO_BOX = 222
    ICON_PRIORITY = 223
    ICON_LAYERS_ISO = 224
    ICON_LAYERS2 = 225
    ICON_MLAYERS = 226
    ICON_MAPS = 227
    ICON_HOT = 228
    ICON_229 = 229
    ICON_230 = 230
    ICON_231 = 231
    ICON_232 = 232
    ICON_233 = 233
    ICON_234 = 234
    ICON_235 = 235
    ICON_236 = 236
    ICON_237 = 237
    ICON_238 = 238
    ICON_239 = 239
    ICON_240 = 240
    ICON_241 = 241
    ICON_242 = 242
    ICON_243 = 243
    ICON_244 = 244
    ICON_245 = 245
    ICON_246 = 246
    ICON_247 = 247
    ICON_248 = 248
    ICON_249 = 249
    ICON_250 = 250
    ICON_251 = 251
    ICON_252 = 252
    ICON_253 = 253
    ICON_254 = 254
    ICON_255 = 255


RAYLIB_VERSION_MAJOR: int
RAYLIB_VERSION_MINOR: int
RAYLIB_VERSION_PATCH: int
RAYLIB_VERSION: str
PI: float
DEG2RAD: Incomplete
RAD2DEG: Incomplete
MOUSE_LEFT_BUTTON: Incomplete
MOUSE_RIGHT_BUTTON: Incomplete
MOUSE_MIDDLE_BUTTON: Incomplete
MATERIAL_MAP_DIFFUSE: Incomplete
MATERIAL_MAP_SPECULAR: Incomplete
SHADER_LOC_MAP_DIFFUSE: Incomplete
SHADER_LOC_MAP_SPECULAR: Incomplete
EPSILON: float
RLGL_VERSION: str
RL_DEFAULT_BATCH_BUFFER_ELEMENTS: int
RL_DEFAULT_BATCH_BUFFERS: int
RL_DEFAULT_BATCH_DRAWCALLS: int
RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS: int
RL_MAX_MATRIX_STACK_SIZE: int
RL_MAX_SHADER_LOCATIONS: int
RL_TEXTURE_WRAP_S: int
RL_TEXTURE_WRAP_T: int
RL_TEXTURE_MAG_FILTER: int
RL_TEXTURE_MIN_FILTER: int
RL_TEXTURE_FILTER_NEAREST: int
RL_TEXTURE_FILTER_LINEAR: int
RL_TEXTURE_FILTER_MIP_NEAREST: int
RL_TEXTURE_FILTER_NEAREST_MIP_LINEAR: int
RL_TEXTURE_FILTER_LINEAR_MIP_NEAREST: int
RL_TEXTURE_FILTER_MIP_LINEAR: int
RL_TEXTURE_FILTER_ANISOTROPIC: int
RL_TEXTURE_MIPMAP_BIAS_RATIO: int
RL_TEXTURE_WRAP_REPEAT: int
RL_TEXTURE_WRAP_CLAMP: int
RL_TEXTURE_WRAP_MIRROR_REPEAT: int
RL_TEXTURE_WRAP_MIRROR_CLAMP: int
RL_MODELVIEW: int
RL_PROJECTION: int
RL_TEXTURE: int
RL_LINES: int
RL_TRIANGLES: int
RL_QUADS: int
RL_UNSIGNED_BYTE: int
RL_FLOAT: int
RL_STREAM_DRAW: int
RL_STREAM_READ: int
RL_STREAM_COPY: int
RL_STATIC_DRAW: int
RL_STATIC_READ: int
RL_STATIC_COPY: int
RL_DYNAMIC_DRAW: int
RL_DYNAMIC_READ: int
RL_DYNAMIC_COPY: int
RL_FRAGMENT_SHADER: int
RL_VERTEX_SHADER: int
RL_COMPUTE_SHADER: int
RL_ZERO: int
RL_ONE: int
RL_SRC_COLOR: int
RL_ONE_MINUS_SRC_COLOR: int
RL_SRC_ALPHA: int
RL_ONE_MINUS_SRC_ALPHA: int
RL_DST_ALPHA: int
RL_ONE_MINUS_DST_ALPHA: int
RL_DST_COLOR: int
RL_ONE_MINUS_DST_COLOR: int
RL_SRC_ALPHA_SATURATE: int
RL_CONSTANT_COLOR: int
RL_ONE_MINUS_CONSTANT_COLOR: int
RL_CONSTANT_ALPHA: int
RL_ONE_MINUS_CONSTANT_ALPHA: int
RL_FUNC_ADD: int
RL_MIN: int
RL_MAX: int
RL_FUNC_SUBTRACT: int
RL_FUNC_REVERSE_SUBTRACT: int
RL_BLEND_EQUATION: int
RL_BLEND_EQUATION_RGB: int
RL_BLEND_EQUATION_ALPHA: int
RL_BLEND_DST_RGB: int
RL_BLEND_SRC_RGB: int
RL_BLEND_DST_ALPHA: int
RL_BLEND_SRC_ALPHA: int
RL_BLEND_COLOR: int
RL_READ_FRAMEBUFFER: int
RL_DRAW_FRAMEBUFFER: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_POSITION: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_NORMAL: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_COLOR: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_TANGENT: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_TEXCOORD2: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_INDICES: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEIDS: int
RL_DEFAULT_SHADER_ATTRIB_LOCATION_BONEWEIGHTS: int
RL_SHADER_LOC_MAP_DIFFUSE: Incomplete
RL_SHADER_LOC_MAP_SPECULAR: Incomplete
GL_SHADING_LANGUAGE_VERSION: int
GL_COMPRESSED_RGB_S3TC_DXT1_EXT: int
GL_COMPRESSED_RGBA_S3TC_DXT1_EXT: int
GL_COMPRESSED_RGBA_S3TC_DXT3_EXT: int
GL_COMPRESSED_RGBA_S3TC_DXT5_EXT: int
GL_ETC1_RGB8_OES: int
GL_COMPRESSED_RGB8_ETC2: int
GL_COMPRESSED_RGBA8_ETC2_EAC: int
GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG: int
GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG: int
GL_COMPRESSED_RGBA_ASTC_4x4_KHR: int
GL_COMPRESSED_RGBA_ASTC_8x8_KHR: int
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT: int
GL_TEXTURE_MAX_ANISOTROPY_EXT: int
GL_PROGRAM_POINT_SIZE: int
GL_LINE_WIDTH: int
GL_UNSIGNED_SHORT_5_6_5: int
GL_UNSIGNED_SHORT_5_5_5_1: int
GL_UNSIGNED_SHORT_4_4_4_4: int
GL_LUMINANCE: int
GL_LUMINANCE_ALPHA: int
RL_DEFAULT_SHADER_ATTRIB_NAME_POSITION: str
RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD: str
RL_DEFAULT_SHADER_ATTRIB_NAME_NORMAL: str
RL_DEFAULT_SHADER_ATTRIB_NAME_COLOR: str
RL_DEFAULT_SHADER_ATTRIB_NAME_TANGENT: str
RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD2: str
RL_DEFAULT_SHADER_ATTRIB_NAME_BONEIDS: str
RL_DEFAULT_SHADER_ATTRIB_NAME_BONEWEIGHTS: str
RL_DEFAULT_SHADER_UNIFORM_NAME_MVP: str
RL_DEFAULT_SHADER_UNIFORM_NAME_VIEW: str
RL_DEFAULT_SHADER_UNIFORM_NAME_PROJECTION: str
RL_DEFAULT_SHADER_UNIFORM_NAME_MODEL: str
RL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL: str
RL_DEFAULT_SHADER_UNIFORM_NAME_COLOR: str
RL_DEFAULT_SHADER_UNIFORM_NAME_BONE_MATRICES: str
RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE0: str
RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE1: str
RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE2: str
RAYGUI_VERSION_MAJOR: int
RAYGUI_VERSION_MINOR: int
RAYGUI_VERSION_PATCH: int
RAYGUI_VERSION: str
SCROLLBAR_LEFT_SIDE: int
SCROLLBAR_RIGHT_SIDE: int
RAYGUI_ICON_SIZE: int
RAYGUI_ICON_MAX_ICONS: int
RAYGUI_ICON_MAX_NAME_LENGTH: int
RAYGUI_MAX_CONTROLS: int
RAYGUI_MAX_PROPS_BASE: int
RAYGUI_MAX_PROPS_EXTENDED: int
KEY_RIGHT: int
KEY_LEFT: int
KEY_DOWN: int
KEY_UP: int
KEY_BACKSPACE: int
KEY_ENTER: int
RAYGUI_WINDOWBOX_STATUSBAR_HEIGHT: int
RAYGUI_GROUPBOX_LINE_THICK: int
RAYGUI_LINE_MARGIN_TEXT: int
RAYGUI_LINE_TEXT_PADDING: int
RAYGUI_PANEL_BORDER_WIDTH: int
RAYGUI_TABBAR_ITEM_WIDTH: int
RAYGUI_MIN_SCROLLBAR_WIDTH: int
RAYGUI_MIN_SCROLLBAR_HEIGHT: int
RAYGUI_MIN_MOUSE_WHEEL_SPEED: int
RAYGUI_TOGGLEGROUP_MAX_ITEMS: int
RAYGUI_TEXTBOX_AUTO_CURSOR_COOLDOWN: int
RAYGUI_TEXTBOX_AUTO_CURSOR_DELAY: int
RAYGUI_VALUEBOX_MAX_CHARS: int
RAYGUI_COLORBARALPHA_CHECKED_SIZE: int
RAYGUI_MESSAGEBOX_BUTTON_HEIGHT: int
RAYGUI_MESSAGEBOX_BUTTON_PADDING: int
RAYGUI_TEXTINPUTBOX_BUTTON_HEIGHT: int
RAYGUI_TEXTINPUTBOX_BUTTON_PADDING: int
RAYGUI_TEXTINPUTBOX_HEIGHT: int
RAYGUI_GRID_ALPHA: float
MAX_LINE_BUFFER_SIZE: int
ICON_TEXT_PADDING: int
RAYGUI_MAX_TEXT_LINES: int
RAYGUI_TEXTSPLIT_MAX_ITEMS: int
RAYGUI_TEXTSPLIT_MAX_TEXT_SIZE: int
RAYGUI_TEXTFORMAT_MAX_SIZE: int
PHYSAC_MAX_BODIES: int
PHYSAC_MAX_MANIFOLDS: int
PHYSAC_MAX_VERTICES: int
PHYSAC_CIRCLE_VERTICES: int
PHYSAC_COLLISION_ITERATIONS: int
PHYSAC_PENETRATION_ALLOWANCE: float
PHYSAC_PENETRATION_CORRECTION: float
PHYSAC_FLT_MAX: float
PHYSAC_EPSILON: float
GLFW_VERSION_MAJOR: int
GLFW_VERSION_MINOR: int
GLFW_VERSION_REVISION: int
GLFW_TRUE: int
GLFW_FALSE: int
GLFW_RELEASE: int
GLFW_PRESS: int
GLFW_REPEAT: int
GLFW_HAT_CENTERED: int
GLFW_HAT_UP: int
GLFW_HAT_RIGHT: int
GLFW_HAT_DOWN: int
GLFW_HAT_LEFT: int
GLFW_KEY_SPACE: int
GLFW_KEY_APOSTROPHE: int
GLFW_KEY_COMMA: int
GLFW_KEY_MINUS: int
GLFW_KEY_PERIOD: int
GLFW_KEY_SLASH: int
GLFW_KEY_0: int
GLFW_KEY_1: int
GLFW_KEY_2: int
GLFW_KEY_3: int
GLFW_KEY_4: int
GLFW_KEY_5: int
GLFW_KEY_6: int
GLFW_KEY_7: int
GLFW_KEY_8: int
GLFW_KEY_9: int
GLFW_KEY_SEMICOLON: int
GLFW_KEY_EQUAL: int
GLFW_KEY_A: int
GLFW_KEY_B: int
GLFW_KEY_C: int
GLFW_KEY_D: int
GLFW_KEY_E: int
GLFW_KEY_F: int
GLFW_KEY_G: int
GLFW_KEY_H: int
GLFW_KEY_I: int
GLFW_KEY_J: int
GLFW_KEY_K: int
GLFW_KEY_L: int
GLFW_KEY_M: int
GLFW_KEY_N: int
GLFW_KEY_O: int
GLFW_KEY_P: int
GLFW_KEY_Q: int
GLFW_KEY_R: int
GLFW_KEY_S: int
GLFW_KEY_T: int
GLFW_KEY_U: int
GLFW_KEY_V: int
GLFW_KEY_W: int
GLFW_KEY_X: int
GLFW_KEY_Y: int
GLFW_KEY_Z: int
GLFW_KEY_LEFT_BRACKET: int
GLFW_KEY_BACKSLASH: int
GLFW_KEY_RIGHT_BRACKET: int
GLFW_KEY_GRAVE_ACCENT: int
GLFW_KEY_WORLD_1: int
GLFW_KEY_WORLD_2: int
GLFW_KEY_ESCAPE: int
GLFW_KEY_ENTER: int
GLFW_KEY_TAB: int
GLFW_KEY_BACKSPACE: int
GLFW_KEY_INSERT: int
GLFW_KEY_DELETE: int
GLFW_KEY_RIGHT: int
GLFW_KEY_LEFT: int
GLFW_KEY_DOWN: int
GLFW_KEY_UP: int
GLFW_KEY_PAGE_UP: int
GLFW_KEY_PAGE_DOWN: int
GLFW_KEY_HOME: int
GLFW_KEY_END: int
GLFW_KEY_CAPS_LOCK: int
GLFW_KEY_SCROLL_LOCK: int
GLFW_KEY_NUM_LOCK: int
GLFW_KEY_PRINT_SCREEN: int
GLFW_KEY_PAUSE: int
GLFW_KEY_F1: int
GLFW_KEY_F2: int
GLFW_KEY_F3: int
GLFW_KEY_F4: int
GLFW_KEY_F5: int
GLFW_KEY_F6: int
GLFW_KEY_F7: int
GLFW_KEY_F8: int
GLFW_KEY_F9: int
GLFW_KEY_F10: int
GLFW_KEY_F11: int
GLFW_KEY_F12: int
GLFW_KEY_F13: int
GLFW_KEY_F14: int
GLFW_KEY_F15: int
GLFW_KEY_F16: int
GLFW_KEY_F17: int
GLFW_KEY_F18: int
GLFW_KEY_F19: int
GLFW_KEY_F20: int
GLFW_KEY_F21: int
GLFW_KEY_F22: int
GLFW_KEY_F23: int
GLFW_KEY_F24: int
GLFW_KEY_F25: int
GLFW_KEY_KP_0: int
GLFW_KEY_KP_1: int
GLFW_KEY_KP_2: int
GLFW_KEY_KP_3: int
GLFW_KEY_KP_4: int
GLFW_KEY_KP_5: int
GLFW_KEY_KP_6: int
GLFW_KEY_KP_7: int
GLFW_KEY_KP_8: int
GLFW_KEY_KP_9: int
GLFW_KEY_KP_DECIMAL: int
GLFW_KEY_KP_DIVIDE: int
GLFW_KEY_KP_MULTIPLY: int
GLFW_KEY_KP_SUBTRACT: int
GLFW_KEY_KP_ADD: int
GLFW_KEY_KP_ENTER: int
GLFW_KEY_KP_EQUAL: int
GLFW_KEY_LEFT_SHIFT: int
GLFW_KEY_LEFT_CONTROL: int
GLFW_KEY_LEFT_ALT: int
GLFW_KEY_LEFT_SUPER: int
GLFW_KEY_RIGHT_SHIFT: int
GLFW_KEY_RIGHT_CONTROL: int
GLFW_KEY_RIGHT_ALT: int
GLFW_KEY_RIGHT_SUPER: int
GLFW_KEY_MENU: int
GLFW_MOD_SHIFT: int
GLFW_MOD_CONTROL: int
GLFW_MOD_ALT: int
GLFW_MOD_SUPER: int
GLFW_MOD_CAPS_LOCK: int
GLFW_MOD_NUM_LOCK: int
GLFW_MOUSE_BUTTON_1: int
GLFW_MOUSE_BUTTON_2: int
GLFW_MOUSE_BUTTON_3: int
GLFW_MOUSE_BUTTON_4: int
GLFW_MOUSE_BUTTON_5: int
GLFW_MOUSE_BUTTON_6: int
GLFW_MOUSE_BUTTON_7: int
GLFW_MOUSE_BUTTON_8: int
GLFW_JOYSTICK_1: int
GLFW_JOYSTICK_2: int
GLFW_JOYSTICK_3: int
GLFW_JOYSTICK_4: int
GLFW_JOYSTICK_5: int
GLFW_JOYSTICK_6: int
GLFW_JOYSTICK_7: int
GLFW_JOYSTICK_8: int
GLFW_JOYSTICK_9: int
GLFW_JOYSTICK_10: int
GLFW_JOYSTICK_11: int
GLFW_JOYSTICK_12: int
GLFW_JOYSTICK_13: int
GLFW_JOYSTICK_14: int
GLFW_JOYSTICK_15: int
GLFW_JOYSTICK_16: int
GLFW_GAMEPAD_BUTTON_A: int
GLFW_GAMEPAD_BUTTON_B: int
GLFW_GAMEPAD_BUTTON_X: int
GLFW_GAMEPAD_BUTTON_Y: int
GLFW_GAMEPAD_BUTTON_LEFT_BUMPER: int
GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER: int
GLFW_GAMEPAD_BUTTON_BACK: int
GLFW_GAMEPAD_BUTTON_START: int
GLFW_GAMEPAD_BUTTON_GUIDE: int
GLFW_GAMEPAD_BUTTON_LEFT_THUMB: int
GLFW_GAMEPAD_BUTTON_RIGHT_THUMB: int
GLFW_GAMEPAD_BUTTON_DPAD_UP: int
GLFW_GAMEPAD_BUTTON_DPAD_RIGHT: int
GLFW_GAMEPAD_BUTTON_DPAD_DOWN: int
GLFW_GAMEPAD_BUTTON_DPAD_LEFT: int
GLFW_GAMEPAD_AXIS_LEFT_X: int
GLFW_GAMEPAD_AXIS_LEFT_Y: int
GLFW_GAMEPAD_AXIS_RIGHT_X: int
GLFW_GAMEPAD_AXIS_RIGHT_Y: int
GLFW_GAMEPAD_AXIS_LEFT_TRIGGER: int
GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER: int
GLFW_NO_ERROR: int
GLFW_NOT_INITIALIZED: int
GLFW_NO_CURRENT_CONTEXT: int
GLFW_INVALID_ENUM: int
GLFW_INVALID_VALUE: int
GLFW_OUT_OF_MEMORY: int
GLFW_API_UNAVAILABLE: int
GLFW_VERSION_UNAVAILABLE: int
GLFW_PLATFORM_ERROR: int
GLFW_FORMAT_UNAVAILABLE: int
GLFW_NO_WINDOW_CONTEXT: int
GLFW_CURSOR_UNAVAILABLE: int
GLFW_FEATURE_UNAVAILABLE: int
GLFW_FEATURE_UNIMPLEMENTED: int
GLFW_PLATFORM_UNAVAILABLE: int
GLFW_FOCUSED: int
GLFW_ICONIFIED: int
GLFW_RESIZABLE: int
GLFW_VISIBLE: int
GLFW_DECORATED: int
GLFW_AUTO_ICONIFY: int
GLFW_FLOATING: int
GLFW_MAXIMIZED: int
GLFW_CENTER_CURSOR: int
GLFW_TRANSPARENT_FRAMEBUFFER: int
GLFW_HOVERED: int
GLFW_FOCUS_ON_SHOW: int
GLFW_MOUSE_PASSTHROUGH: int
GLFW_POSITION_X: int
GLFW_POSITION_Y: int
GLFW_RED_BITS: int
GLFW_GREEN_BITS: int
GLFW_BLUE_BITS: int
GLFW_ALPHA_BITS: int
GLFW_DEPTH_BITS: int
GLFW_STENCIL_BITS: int
GLFW_ACCUM_RED_BITS: int
GLFW_ACCUM_GREEN_BITS: int
GLFW_ACCUM_BLUE_BITS: int
GLFW_ACCUM_ALPHA_BITS: int
GLFW_AUX_BUFFERS: int
GLFW_STEREO: int
GLFW_SAMPLES: int
GLFW_SRGB_CAPABLE: int
GLFW_REFRESH_RATE: int
GLFW_DOUBLEBUFFER: int
GLFW_CLIENT_API: int
GLFW_CONTEXT_VERSION_MAJOR: int
GLFW_CONTEXT_VERSION_MINOR: int
GLFW_CONTEXT_REVISION: int
GLFW_CONTEXT_ROBUSTNESS: int
GLFW_OPENGL_FORWARD_COMPAT: int
GLFW_CONTEXT_DEBUG: int
GLFW_OPENGL_PROFILE: int
GLFW_CONTEXT_RELEASE_BEHAVIOR: int
GLFW_CONTEXT_NO_ERROR: int
GLFW_CONTEXT_CREATION_API: int
GLFW_SCALE_TO_MONITOR: int
GLFW_SCALE_FRAMEBUFFER: int
GLFW_COCOA_RETINA_FRAMEBUFFER: int
GLFW_COCOA_FRAME_NAME: int
GLFW_COCOA_GRAPHICS_SWITCHING: int
GLFW_X11_CLASS_NAME: int
GLFW_X11_INSTANCE_NAME: int
GLFW_WIN32_KEYBOARD_MENU: int
GLFW_WIN32_SHOWDEFAULT: int
GLFW_WAYLAND_APP_ID: int
GLFW_NO_API: int
GLFW_OPENGL_API: int
GLFW_OPENGL_ES_API: int
GLFW_NO_ROBUSTNESS: int
GLFW_NO_RESET_NOTIFICATION: int
GLFW_LOSE_CONTEXT_ON_RESET: int
GLFW_OPENGL_ANY_PROFILE: int
GLFW_OPENGL_CORE_PROFILE: int
GLFW_OPENGL_COMPAT_PROFILE: int
GLFW_CURSOR: int
GLFW_STICKY_KEYS: int
GLFW_STICKY_MOUSE_BUTTONS: int
GLFW_LOCK_KEY_MODS: int
GLFW_RAW_MOUSE_MOTION: int
GLFW_CURSOR_NORMAL: int
GLFW_CURSOR_HIDDEN: int
GLFW_CURSOR_DISABLED: int
GLFW_CURSOR_CAPTURED: int
GLFW_ANY_RELEASE_BEHAVIOR: int
GLFW_RELEASE_BEHAVIOR_FLUSH: int
GLFW_RELEASE_BEHAVIOR_NONE: int
GLFW_NATIVE_CONTEXT_API: int
GLFW_EGL_CONTEXT_API: int
GLFW_OSMESA_CONTEXT_API: int
GLFW_ANGLE_PLATFORM_TYPE_NONE: int
GLFW_ANGLE_PLATFORM_TYPE_OPENGL: int
GLFW_ANGLE_PLATFORM_TYPE_OPENGLES: int
GLFW_ANGLE_PLATFORM_TYPE_D3D9: int
GLFW_ANGLE_PLATFORM_TYPE_D3D11: int
GLFW_ANGLE_PLATFORM_TYPE_VULKAN: int
GLFW_ANGLE_PLATFORM_TYPE_METAL: int
GLFW_WAYLAND_PREFER_LIBDECOR: int
GLFW_WAYLAND_DISABLE_LIBDECOR: int
GLFW_ANY_POSITION: int
GLFW_ARROW_CURSOR: int
GLFW_IBEAM_CURSOR: int
GLFW_CROSSHAIR_CURSOR: int
GLFW_POINTING_HAND_CURSOR: int
GLFW_RESIZE_EW_CURSOR: int
GLFW_RESIZE_NS_CURSOR: int
GLFW_RESIZE_NWSE_CURSOR: int
GLFW_RESIZE_NESW_CURSOR: int
GLFW_RESIZE_ALL_CURSOR: int
GLFW_NOT_ALLOWED_CURSOR: int
GLFW_CONNECTED: int
GLFW_DISCONNECTED: int
GLFW_JOYSTICK_HAT_BUTTONS: int
GLFW_ANGLE_PLATFORM_TYPE: int
GLFW_PLATFORM: int
GLFW_COCOA_CHDIR_RESOURCES: int
GLFW_COCOA_MENUBAR: int
GLFW_X11_XCB_VULKAN_SURFACE: int
GLFW_WAYLAND_LIBDECOR: int
GLFW_ANY_PLATFORM: int
GLFW_PLATFORM_WIN32: int
GLFW_PLATFORM_COCOA: int
GLFW_PLATFORM_WAYLAND: int
GLFW_PLATFORM_X11: int
GLFW_PLATFORM_NULL: int

LIGHTGRAY: Incomplete
GRAY: Incomplete
DARKGRAY: Incomplete
YELLOW: Incomplete
GOLD: Incomplete
ORANGE: Incomplete
PINK: Incomplete
RED: Incomplete
MAROON: Incomplete
GREEN: Incomplete
LIME: Incomplete
DARKGREEN: Incomplete
SKYBLUE: Incomplete
BLUE: Incomplete
DARKBLUE: Incomplete
PURPLE: Incomplete
VIOLET: Incomplete
DARKPURPLE: Incomplete
BEIGE: Incomplete
BROWN: Incomplete
DARKBROWN: Incomplete
WHITE: Incomplete
BLACK: Incomplete
BLANK: Incomplete
MAGENTA: Incomplete
RAYWHITE: Incomplete

THIS_DIR: Incomplete
REPO_ROOT: Incomplete
RAYLIB_PLATFORM: Incomplete


ffibuilder: Incomplete

ffi: _cffi_backend.FFI


def __getattr__(name: str) -> Any: ...
