name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Build package
        run: make dist

      - name: Publish to Itch.io
        uses: Oval-Tutu/publish-to-itch-with-butler@v1
        with:
          api-key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: zqian
          itch_game: pac-man
          channel: linux
          package: ./dist/pac-man.zip
